FROM python:3
ENV PYTHONBUFFERED 1

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# COPY . /usr/src/app 와 같음
COPY . .

# CMD 'python manage.py runserver 0.0.0.0:8000'